services:
  bot-light:
    profiles: ["light"]
    build:
      context: .
      args:
        VARIANT: light
    env_file:
      - .env
    environment:
      - OCR_MODULE_PRIORITY=openrouter,yandex_ocr
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped

  bot-full:
    profiles: ["full"]
    build:
      context: .
      args:
        VARIANT: full
    env_file:
      - .env
    environment:
      - OCR_MODULE_PRIORITY=openrouter,yandex_ocr,rupasportread
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped