version: '3.8'

services:
  bot-light:
    profiles: ["light"]
    build:
      context: .
      args:
        VARIANT: light
    env_file:
      - .env
    environment:
      - OCR_MODULE_PRIORITY=openrouter,yandex_ocr
    network_mode: host
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped

  bot-full:
    profiles: ["full"]
    build:
      context: .
      args:
        VARIANT: full
    env_file:
      - .env
    environment:
      - OCR_MODULE_PRIORITY=openrouter,yandex_ocr,rupasportread
    network_mode: host
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped
